package dev.yukiho.cers.db.model;

import java.util.Date;

public class Event {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.id
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.student_id
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.mode
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    private Integer mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.accepted_at
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    private Date acceptedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.created_at
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.id
     *
     * @return the value of event.id
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.id
     *
     * @param id the value for event.id
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.student_id
     *
     * @return the value of event.student_id
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.student_id
     *
     * @param studentId the value for event.student_id
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.mode
     *
     * @return the value of event.mode
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.mode
     *
     * @param mode the value for event.mode
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.accepted_at
     *
     * @return the value of event.accepted_at
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public Date getAcceptedAt() {
        return acceptedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.accepted_at
     *
     * @param acceptedAt the value for event.accepted_at
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public void setAcceptedAt(Date acceptedAt) {
        this.acceptedAt = acceptedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.created_at
     *
     * @return the value of event.created_at
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.created_at
     *
     * @param createdAt the value for event.created_at
     *
     * @mbg.generated Wed Mar 18 03:26:10 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}